/*
 * game_interface.h
 *
 *  Created on: Jan 16, 2026
 *      Author: lucasnascimento
 */

#ifndef INC_GAMES_GAME_INTERFACE_H_
#define INC_GAMES_GAME_INTERFACE_H_

enum Codes : uint8_t {
	END = 0X00,
	HIT_BODY = 0X01,
	HIT_WALL = 0X02,

	FOOD = 0X03,
	FOOD_POISON = 0X04,
	FOOD_BOOST_SPEED = 0X05,
	FOOD_DIVIDE = 0X06,
	FOOD_EXPLODE = 0X07,
	FOOD_BOOST_POINT = 0X08,
	FOOD_MURF_SPEED = 0X09,

	SPACE_MYCRAFT = 0X50,
	SPACE_ENEMYCRAFT = 0X51,

	PONG_PAD = 0XE0,
	PONG_BLOCK = 0XE1,
	BODY = 0XF0,
	VOID = 0XF1,
	PASS = 0XFF,
};


enum SpaceGameCodes : uint8_t {
	BULLET_TYPE_PISTOL = 0X01,
	BULLET_TYPE_ROCKET = 0X02,


	SPACE_CRAFT_HIT = 0X20,

	SPACECRAFT_ORIENTATION_N = 0X90,
	SPACECRAFT_ORIENTATION_S = 0X91,
	SPACECRAFT_ORIENTATION_E = 0X92,
	SPACECRAFT_ORIENTATION_W = 0X93,
	SPACECRAFT_ORIENTATION_NE = 0X94,
	SPACECRAFT_ORIENTATION_NW = 0X95,
	SPACECRAFT_ORIENTATION_SE = 0X96,
	SPACECRAFT_ORIENTATION_SW = 0X97,

	AMMO = 0XA0,

	DESTROY = 0XB0,
	OVERWRITE = 0XB1,
	DESTROY_BOTH = 0XB2,
};




#endif /* INC_GAMES_GAME_INTERFACE_H_ */
